import { notFound } from "next/navigation";
import { getPublicService } from "@/lib/commercial/data";
import { Breadcrumbs } from "@/components/layout/breadcrumbs";
import { ContactLink } from "@/components/contact-link";
import { JsonLd } from "@/components/editorial/json-ld";
import { absoluteUrl, noindexRobotsMetadata, ORGANIZATION_ID, resolveCanonical, robotsMetadata } from "@/lib/editorial/seo";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=await getPublicService(slug);if(!s)return {title:"Solução não encontrada",robots:{index:false,follow:false}};const canonical=resolveCanonical(`/solucoes/${s.slug}`,s.seo.canonicalUrl);return {title:s.seo.metaTitle||`${s.title} | Crescimento Vertical`,description:s.seo.metaDescription||s.shortDescription,robots:s.seo.noindex?noindexRobotsMetadata():robotsMetadata(),alternates:{canonical},openGraph:{title:s.seo.metaTitle||s.title,description:s.seo.metaDescription||s.shortDescription,url:canonical,type:"website",siteName:"Crescimento Vertical",locale:"pt_BR"},twitter:{card:"summary",title:s.seo.metaTitle||s.title,description:s.seo.metaDescription||s.shortDescription}};}
export default async function Solution({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=await getPublicService(slug);if(!s)notFound();const url=absoluteUrl(`/solucoes/${s.slug}`);const jsonLd={"@context":"https://schema.org","@type":"Service","@id":`${url}#service`,name:s.title,description:s.shortDescription,url,provider:{"@id":ORGANIZATION_ID}};return <div className="section-pad"><JsonLd data={jsonLd}/><div className="container-shell"><Breadcrumbs items={[{name:"Início",href:"/"},{name:"Soluções",href:"/solucoes"},{name:s.title,href:`/solucoes/${s.slug}`}]}/><p className="section-kicker">{s.title}</p><h1 className="section-title">{s.positioning||s.shortDescription}</h1><p className="section-copy">{s.shortDescription}</p><div className="grid gap-8 md:grid-cols-2"><Info title="Para quem é" items={[s.targetAudience||"Empresas que buscam estrutura digital."]}/><Info title="Problemas atendidos" items={s.problems}/><Info title="Capacidades" items={s.capabilities}/><Info title="Entregáveis" items={s.deliverables}/><Info title="Processo" items={s.processSteps}/></div><div className="mt-12"><ContactLink className="button-primary">Solicitar diagnóstico ↗</ContactLink></div></div></div>}
function Info({title,items}:{title:string,items:string[]}){return <section><h2 className="text-2xl font-semibold">{title}</h2><ul className="mt-3 space-y-2 text-slate-300">{items.map((x,i)=><li key={`${x}-${i}`}>• {x}</li>)}</ul></section>}
