"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

export function DiagnosticForm() {
  const [token,setToken]=useState(""), [hash,setHash]=useState(""), [version,setVersion]=useState(""), [state,setState]=useState<"idle"|"sending"|"success"|"error">("idle"), [error,setError]=useState(""), [startedAt]=useState(()=>Date.now());
  useEffect(()=>{void fetch("/api/measure",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"form_start",source:"diagnostico"})});fetch("/api/leads").then(r=>r.json()).then(v=>{setToken(v.token||"");setHash(v.consentTextHash||"");setVersion(v.consentVersion||"")}).catch(()=>setState("error"))},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault(); if(state==="sending")return; const form=event.currentTarget, data=new FormData(form), payload:Record<string,string|boolean>=Object.fromEntries(data.entries()) as Record<string,string|boolean>; payload.consent=data.get("consent")==="on"; payload.startedAt=form.dataset.startedAt||String(Date.now()); payload.formToken=token; payload.consentTextHash=hash; payload.consentVersion=version; payload.idempotencyKey=crypto.randomUUID(); setState("sending"); setError(""); void fetch("/api/measure",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"form_attempt",source:"diagnostico"})}); try {const r=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}); const v=await r.json(); if(!r.ok||!v.ok)throw new Error(v.error); void fetch("/api/measure",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"form_success",source:"diagnostico"})}); form.reset();setState("success")}catch(e){void fetch("/api/measure",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"form_failure",source:"diagnostico"})});setError(e instanceof Error?e.message:"Não foi possível enviar agora.");setState("error")}}
  if(state==="success") return <div className="rounded-xl border border-cyan-400/30 bg-slate-900/70 p-6" role="status"><h2 className="text-xl font-semibold text-white">Recebemos sua solicitação.</h2><p className="mt-2 text-slate-300">Vamos analisar o contexto enviado e retornar pelo canal escolhido.</p><button className="button-secondary mt-5" onClick={()=>setState("idle")}>Enviar outra solicitação</button></div>;
  return <form onSubmit={submit} className="mt-10 grid max-w-2xl gap-5" aria-describedby="diagnostico-ajuda diagnostico-erros" data-started-at={startedAt}>
    <p id="diagnostico-ajuda" className="text-sm text-slate-300">Preencha o contexto necessário para uma conversa objetiva. Campos com * são obrigatórios.</p>
    <div><label htmlFor="lead-name">Nome *</label><input id="lead-name" name="name" required autoComplete="name" /></div>
    <div><label htmlFor="lead-email">E-mail *</label><input id="lead-email" name="email" type="email" required autoComplete="email" /></div>
    <div><label htmlFor="lead-phone">Telefone</label><input id="lead-phone" name="phone" autoComplete="tel" /></div>
    <div><label htmlFor="lead-company">Empresa</label><input id="lead-company" name="company" autoComplete="organization" /></div>
    <div><label htmlFor="lead-service">Serviço de interesse *</label><select id="lead-service" name="serviceInterest" required defaultValue=""><option value="" disabled>Selecione</option><option value="sites">Sites e conversão</option><option value="automation">Automação empresarial</option><option value="ai">IA aplicada a negócios</option><option value="performance">Performance digital</option></select></div>
    <div><label htmlFor="lead-context">Contexto operacional</label><textarea id="lead-context" name="operationalContext" rows={3} /></div>
    <div><label htmlFor="lead-challenge">Desafio principal *</label><textarea id="lead-challenge" name="challenge" required rows={4} /></div>
    <div><label htmlFor="lead-preference">Preferência de contato *</label><select id="lead-preference" name="contactPreference" required defaultValue=""><option value="" disabled>Selecione</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="whatsapp">WhatsApp</option></select></div>
    <input name="source" type="hidden" value="diagnostico" /><input name="sourcePage" type="hidden" value="/diagnostico" /><input name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" className="sr-only" />
    <label className="flex items-start gap-3"><input name="consent" type="checkbox" required className="mt-1" /><span>Autorizo o contato para tratar esta solicitação, conforme a versão {version||"atual"} e a <Link href="/privacidade" className="underline">política de privacidade</Link>. Posso revogar a autorização a qualquer momento.</span></label>
    <p id="diagnostico-erros" role="alert" className={state==="error"?"text-red-300":"sr-only"}>{error||""}</p>
    <button className="button-primary" disabled={state==="sending"||!token}>{state==="sending"?"Enviando…":"Solicitar diagnóstico"}</button>
  </form>;
}
