import { unstable_cache } from "next/cache";
import { getPayload } from "payload";
import type { Payload } from "payload";
import config from "@payload-config";
import type { PublicCase, PublicService } from "./types";

let payloadPromise: Promise<Payload | null> | null = null;
async function payloadInstance() {
  if (!process.env.DATABASE_URL) return null;
  if (!payloadPromise) payloadPromise = getPayload({ config }).catch(() => null);
  return payloadPromise;
}
const fallback: PublicService[] = [
  {id:"sites",title:"Sites e landing pages",slug:"sites-e-landing-pages",shortDescription:"Sites e landing pages construídos para explicar sua oferta, converter visitantes em contatos e integrar-se aos seus canais de atendimento.",positioning:"Construímos páginas com objetivo claro: comunicar a proposta, orientar o visitante e capturar o próximo passo.",targetAudience:"Empresas sem presença digital estruturada ou cujo site atual informa sem gerar contatos.",problems:["Site que não deixa claro o que a empresa faz","Visitantes que saem sem deixar contato","Páginas lentas ou difíceis de manter","Presença desalinhada com WhatsApp e redes"],deliverables:["Estrutura de páginas e navegação","Landing page de oferta ou campanha","Formulário de contato e CTAs","Integração com WhatsApp e e-mail"],processSteps:["Diagnóstico de posicionamento","Arquitetura de conteúdo","Design e implementação","Publicação e medição"],capabilities:["Conversão orientada por estrutura","Desempenho e responsividade","Manutenção evolutiva"],primaryCTAType:"diagnostic",primaryCTALabel:"Solicitar diagnóstico",featured:true,order:1,seo:{}},
  {id:"trafego",title:"Tráfego e conversão",slug:"trafego-e-conversao",shortDescription:"Campanhas e jornadas planejadas para levar visitantes qualificados a uma estrutura que os converte em contatos.",positioning:"Planejamos aquisição, páginas e mensuração como um só sistema — sem prometer resultados garantidos.",targetAudience:"Empresas que já têm oferta clara e precisam melhorar a previsibilidade da aquisição.",problems:["Campanhas desconectadas do site","Investimento sem mensuração de retorno","Funis que não qualificam o contato","Pouca clareza sobre o próximo passo do lead"],deliverables:["Plano de aquisição e canais","Funil e páginas de destino","Eventos e mensuração de conversão","Otimização contínua"],processSteps:["Contexto e oferta","Plano de tráfego","Execução e criativos","Análise e ajuste"],capabilities:["Criativos orientados a conversão","Jornadas com CTA claro","Mensuração de origem e conversão"],primaryCTAType:"diagnostic",primaryCTALabel:"Solicitar diagnóstico",featured:true,order:2,seo:{}},
  {id:"whatsapp",title:"Automação de WhatsApp",slug:"automacao-whatsapp",shortDescription:"Atendimento inicial, qualificação e encaminhamento automatizados no WhatsApp, preservando a decisão humana.",positioning:"Automatizamos as etapas repetitivas do atendimento para que sua equipe foque no que exige julgamento.",targetAudience:"Operações que recebem volume de contatos no WhatsApp e perdem oportunidades por atraso ou desorganização.",problems:["Respostas lentas fora do horário comercial","Follow-ups esquecidos","Contatos que chegam sem qualificação","Atendimento manual que não acompanha a demanda"],deliverables:["Fluxos de atendimento inicial","Qualificação e encaminhamento","Respostas automáticas com contexto","Registro e acompanhamento de conversas"],processSteps:["Mapeamento do atendimento atual","Desenho dos fluxos","Integração com canais e CRM","Acompanhamento e ajuste"],capabilities:["Atendimento inicial contínuo","Follow-up programado","Integração com ferramentas existentes"],primaryCTAType:"diagnostic",primaryCTALabel:"Solicitar diagnóstico",order:3,seo:{}},
  {id:"agentes",title:"Agentes de IA",slug:"agentes-de-ia",shortDescription:"Agentes de IA especializados, com limites definidos, revisão humana e rastreabilidade de decisão.",positioning:"Aplicamos IA a tarefas bem delimitadas e auditáveis, sempre com supervisão e escopo controlado.",targetAudience:"Equipes que querem assistência de IA em tarefas repetitivas sem abrir mão de controle.",problems:["Informação dispersa entre sistemas","Tarefas manuais repetitivas","IA genérica sem contexto da empresa","Falta de rastreabilidade nas respostas"],deliverables:["Definição de escopo do agente","Bases de conhecimento autorizadas","Fluxos com revisão humana","Registro de decisões e limites"],processSteps:["Descoberta do problema","Prototipação controlada","Validação com casos reais","Operação e monitoramento"],capabilities:["Bases autorizadas","Revisão humana obrigatória","Rastreabilidade e limites"],primaryCTAType:"diagnostic",primaryCTALabel:"Solicitar diagnóstico",order:4,seo:{}},
  {id:"n8n",title:"Integrações n8n",slug:"integracoes-n8n",shortDescription:"Ferramentas conectadas por workflows determinísticos com webhooks, APIs e tratamento de falhas.",positioning:"Orquestramos processos entre sistemas de forma previsível e auditável, sem código disperso.",targetAudience:"Empresas com ferramentas que não conversam entre si e retrabalho manual entre elas.",problems:["Retrabalho copiando dados entre sistemas","Falhas sem visibilidade","Processos dependentes de uma pessoa","Ferramentas isoladas"],deliverables:["Inventário de sistemas e dados","Workflows de integração","Tratamento de erros e retry","Observabilidade e logs"],processSteps:["Inventário e contrato","Implementação dos workflows","Testes de falha","Monitoramento contínuo"],capabilities:["APIs e webhooks","Recuperação de falhas","Auditoria de execução"],primaryCTAType:"diagnostic",primaryCTALabel:"Solicitar diagnóstico",order:5,seo:{}},
  {id:"consultoria",title:"Consultoria e suporte",slug:"consultoria-e-suporte",shortDescription:"Diagnóstico técnico, priorização e evolução recorrente da operação digital da sua empresa.",positioning:"Apoiamos decisões técnicas e a evolução da operação dentro de escopo contratado e com entregas verificáveis.",targetAudience:"Empresas que precisam de direção técnica contínua sem equipe interna dedicada.",problems:["Prioridades difusas de tecnologia","Operação sem revisão periódica","Dependência de soluções pontuais","Falta de um roadmap claro"],deliverables:["Diagnóstico técnico","Roadmap priorizado","Suporte e manutenção","Revisões periódicas"],processSteps:["Contexto e diagnóstico","Priorização","Plano de execução","Revisão e evolução"],capabilities:["Arquitetura e processos","Monitoramento","Relacionamento recorrente"],primaryCTAType:"diagnostic",primaryCTALabel:"Solicitar diagnóstico",order:6,seo:{}},
];
export const COMMERCIAL_FALLBACK_SERVICES = fallback;
function mapService(input: unknown): PublicService { const doc=input as Record<string,unknown>; const seo=(doc.seo&&typeof doc.seo==="object"?doc.seo:{}) as Record<string,unknown>; const arr=(v:unknown)=>Array.isArray(v)?v.map(x=>typeof x==="object"&&x&&"value" in x?String((x as {value:unknown}).value):String(x)):[]; return {id:doc.id as string|number,title:String(doc.title),slug:String(doc.slug),shortDescription:doc.shortDescription as string,positioning:doc.positioning as string,targetAudience:doc.targetAudience as string,problems:arr(doc.problems),deliverables:arr(doc.deliverables),processSteps:arr(doc.processSteps),capabilities:arr(doc.capabilities),primaryCTAType:doc.primaryCTAType as string,primaryCTALabel:doc.primaryCTALabel as string,featured:doc.featured as boolean,order:doc.order as number,seo:{metaTitle:seo.metaTitle as string,metaDescription:seo.metaDescription as string,canonicalUrl:seo.canonicalUrl as string,noindex:seo.noindex as boolean}}; }
const getServicesCached = unstable_cache(async()=>{const p=await payloadInstance(); if(!p)return fallback; const r=await p.find({collection:"services",where:{and:[{active:{equals:true}},{_status:{equals:"published"}},{publishedAt:{less_than_equal:new Date().toISOString()}}]},draft:false,overrideAccess:false,limit:100,sort:"order"}); return r.docs.map(mapService);},["commercial-services"],{revalidate:300,tags:["commercial-services"]});
export const getPublicServices=()=>getServicesCached();
export async function getPublicService(slug:string){return (await getPublicServices()).find((s)=>s.slug===slug)||null;}
export async function getPublicCases():Promise<PublicCase[]> { const p=await payloadInstance(); if(!p)return []; const r=await p.find({collection:"cases",where:{and:[{active:{equals:true}},{authorizationStatus:{equals:"approved"}},{_status:{equals:"published"}},{publishedAt:{less_than_equal:new Date().toISOString()}}]},draft:false,overrideAccess:false,depth:1,limit:100}); return r.docs.map((d)=>{const doc=d as unknown as Record<string,unknown>; const rel=Array.isArray(doc.relatedServices)?doc.relatedServices:[]; const media=doc.media&&typeof doc.media==="object"?doc.media as Record<string,unknown>:null; const seo=doc.seo&&typeof doc.seo==="object"?doc.seo as Record<string,unknown>:{}; return {id:doc.id as string|number,title:String(doc.title),slug:String(doc.slug),summary:doc.summary as string,clientDisplayName:doc.clientDisplayName as string,challenge:doc.challenge as string,solution:doc.solution as string,results:doc.results as string,period:doc.period as string,relatedServices:rel.map(s=>{const x=s as Record<string,unknown>; return {title:String(x.title),slug:String(x.slug)}}),testimonial:doc.testimonial as string,media:media&&{url:media.url as string,alt:media.alt as string},seo:{metaTitle:seo.metaTitle as string,metaDescription:seo.metaDescription as string,canonicalUrl:seo.canonicalUrl as string,noindex:seo.noindex as boolean}}}); }
