import { unstable_cache } from "next/cache";
import { getPayload } from "payload";
import type { Payload } from "payload";
import config from "@payload-config";
import type { PublicCase, PublicService } from "./types";

let payloadPromise: Promise<Payload | null> | null = null;
async function payloadInstance() {
  if (!process.env.DATABASE_URL) return null;
  if (!payloadPromise) payloadPromise = getPayload({ config }).catch(() => null);
  return payloadPromise;
}
const fallback: PublicService[] = [
  {id:"sites",title:"Sites e landing pages",slug:"sites-e-landing-pages",shortDescription:"Presença digital clara, rápida e preparada para orientar o próximo passo.",positioning:"Estruturamos páginas que explicam a proposta e facilitam o contato.",targetAudience:"Empresas que precisam organizar sua presença digital.",problems:["Mensagem dispersa","Jornadas sem próximo passo"],deliverables:["Arquitetura de páginas","Landing pages","Integração com canais"],processSteps:["Diagnóstico","Estrutura","Implementação","Evolução"],capabilities:["Arquitetura de conversão","Desempenho","Manutenção"],primaryCTAType:"diagnostic",primaryCTALabel:"Solicitar diagnóstico",featured:true,order:1,seo:{}},
  {id:"trafego",title:"Tráfego e conversão",slug:"trafego-e-conversao",shortDescription:"Campanhas e jornadas conectadas a uma estrutura de conversão.",positioning:"Planejamos aquisição, páginas e mensuração sem prometer resultados garantidos.",targetAudience:"Empresas que querem melhorar a clareza da aquisição.",problems:["Campanhas desconectadas","Falta de mensuração"],deliverables:["Planejamento","Funis","Otimização"],processSteps:["Contexto","Plano","Execução","Análise"],capabilities:["Criativos","Jornadas","Mensuração"],primaryCTAType:"diagnostic",primaryCTALabel:"Solicitar diagnóstico",featured:true,order:2,seo:{}},
  {id:"whatsapp",title:"Automação de WhatsApp",slug:"automacao-whatsapp",shortDescription:"Atendimento inicial, organização e encaminhamento com contexto.",positioning:"Automatizamos etapas repetitivas preservando a participação humana.",targetAudience:"Operações que recebem contatos pelo WhatsApp.",problems:["Respostas lentas","Follow-ups perdidos"],deliverables:["Fluxos","Qualificação","Encaminhamento"],processSteps:["Mapeamento","Desenho","Integração","Acompanhamento"],capabilities:["Atendimento inicial","Follow-up","Integrações"],primaryCTAType:"diagnostic",primaryCTALabel:"Solicitar diagnóstico",order:3,seo:{}},
  {id:"agentes",title:"Agentes de IA",slug:"agentes-de-ia",shortDescription:"Agentes especializados com limites, revisão e rastreabilidade.",positioning:"Aplicamos IA a tarefas autorizadas e processos observáveis.",targetAudience:"Equipes que querem assistência com responsabilidade.",problems:["Informação dispersa","Tarefas manuais"],deliverables:["Escopo do agente","Bases autorizadas","Controles"],processSteps:["Descoberta","Prototipação","Validação","Operação"],capabilities:["Bases autorizadas","Revisão humana","Rastreabilidade"],primaryCTAType:"diagnostic",primaryCTALabel:"Solicitar diagnóstico",order:4,seo:{}},
  {id:"n8n",title:"Integrações n8n",slug:"integracoes-n8n",shortDescription:"Ferramentas conectadas com webhooks, APIs e tratamento de falhas.",positioning:"Orquestramos processos determinísticos e auditáveis.",targetAudience:"Empresas com ferramentas que não conversam entre si.",problems:["Retrabalho","Falhas sem visibilidade"],deliverables:["Mapeamento","Workflows","Observabilidade"],processSteps:["Inventário","Contrato","Implementação","Monitoramento"],capabilities:["APIs","Webhooks","Recuperação"],primaryCTAType:"diagnostic",primaryCTALabel:"Solicitar diagnóstico",order:5,seo:{}},
  {id:"consultoria",title:"Consultoria e suporte",slug:"consultoria-e-suporte",shortDescription:"Diagnóstico técnico, priorização e melhoria recorrente.",positioning:"Apoiamos decisões e a evolução da operação conforme o escopo contratado.",targetAudience:"Empresas que precisam de direção técnica contínua.",problems:["Prioridades difusas","Operação sem revisão"],deliverables:["Diagnóstico","Roadmap","Suporte"],processSteps:["Contexto","Prioridades","Plano","Revisão"],capabilities:["Arquitetura","Processos","Monitoramento"],primaryCTAType:"diagnostic",primaryCTALabel:"Solicitar diagnóstico",order:6,seo:{}},
];
export const COMMERCIAL_FALLBACK_SERVICES = fallback;
function mapService(input: unknown): PublicService { const doc=input as Record<string,unknown>; const seo=(doc.seo&&typeof doc.seo==="object"?doc.seo:{}) as Record<string,unknown>; const arr=(v:unknown)=>Array.isArray(v)?v.map(x=>typeof x==="object"&&x&&"value" in x?String((x as {value:unknown}).value):String(x)):[]; return {id:doc.id as string|number,title:String(doc.title),slug:String(doc.slug),shortDescription:doc.shortDescription as string,positioning:doc.positioning as string,targetAudience:doc.targetAudience as string,problems:arr(doc.problems),deliverables:arr(doc.deliverables),processSteps:arr(doc.processSteps),capabilities:arr(doc.capabilities),primaryCTAType:doc.primaryCTAType as string,primaryCTALabel:doc.primaryCTALabel as string,featured:doc.featured as boolean,order:doc.order as number,seo:{metaTitle:seo.metaTitle as string,metaDescription:seo.metaDescription as string,canonicalUrl:seo.canonicalUrl as string,noindex:seo.noindex as boolean}}; }
const getServicesCached = unstable_cache(async()=>{const p=await payloadInstance(); if(!p)return fallback; const r=await p.find({collection:"services",where:{and:[{active:{equals:true}},{_status:{equals:"published"}},{publishedAt:{less_than_equal:new Date().toISOString()}}]},draft:false,overrideAccess:false,limit:100,sort:"order"}); return r.docs.map(mapService);},["commercial-services"],{revalidate:300,tags:["commercial-services"]});
export const getPublicServices=()=>getServicesCached();
export async function getPublicService(slug:string){return (await getPublicServices()).find((s)=>s.slug===slug)||null;}
export async function getPublicCases():Promise<PublicCase[]> { const p=await payloadInstance(); if(!p)return []; const r=await p.find({collection:"cases",where:{and:[{active:{equals:true}},{authorizationStatus:{equals:"approved"}},{_status:{equals:"published"}},{publishedAt:{less_than_equal:new Date().toISOString()}}]},draft:false,overrideAccess:false,depth:1,limit:100}); return r.docs.map((d)=>{const doc=d as unknown as Record<string,unknown>; const rel=Array.isArray(doc.relatedServices)?doc.relatedServices:[]; const media=doc.media&&typeof doc.media==="object"?doc.media as Record<string,unknown>:null; const seo=doc.seo&&typeof doc.seo==="object"?doc.seo as Record<string,unknown>:{}; return {id:doc.id as string|number,title:String(doc.title),slug:String(doc.slug),summary:doc.summary as string,clientDisplayName:doc.clientDisplayName as string,challenge:doc.challenge as string,solution:doc.solution as string,results:doc.results as string,period:doc.period as string,relatedServices:rel.map(s=>{const x=s as Record<string,unknown>; return {title:String(x.title),slug:String(x.slug)}}),testimonial:doc.testimonial as string,media:media&&{url:media.url as string,alt:media.alt as string},seo:{metaTitle:seo.metaTitle as string,metaDescription:seo.metaDescription as string,canonicalUrl:seo.canonicalUrl as string,noindex:seo.noindex as boolean}}}); }
