/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    authors: Author;
    categories: Category;
    media: Media;
    sources: Source;
    'research-dossiers': ResearchDossier;
    articles: Article;
    services: Service;
    cases: Case;
    tags: Tag;
    leads: Lead;
    'lead-outbox': LeadOutbox;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    'research-dossiers': ResearchDossiersSelect<false> | ResearchDossiersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'lead-outbox': LeadOutboxSelect<false> | LeadOutboxSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor' | 'reviewer' | 'researcher' | 'automation')[];
  active?: boolean | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug: string;
  biography?: string | null;
  photo?: (number | null) | Media;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  title: string;
  publisher: string;
  url: string;
  sourceType?:
    | (
        | 'official_documentation'
        | 'press'
        | 'technical_publication'
        | 'research_paper'
        | 'social'
        | 'community'
        | 'newsletter'
        | 'aggregator'
        | 'video'
        | 'other'
      )
    | null;
  sourceLevel?: ('A' | 'B' | 'C') | null;
  author?: string | null;
  publishedAt?: string | null;
  collectedAt?: string | null;
  editorialNotes?: string | null;
  reliability: 'unverified' | 'verified' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-dossiers".
 */
export interface ResearchDossier {
  id: number;
  topic: string;
  summary?: string | null;
  keyFindings?:
    | {
        finding: string;
        id?: string | null;
      }[]
    | null;
  sources?: (number | Source)[] | null;
  risksAndDivergences?: string | null;
  status: 'research' | 'validated' | 'rejected';
  provenance?: {
    origin?: ('hermes' | 'manual' | 'import') | null;
    runId?: string | null;
    collectedAt?: string | null;
    notes?: string | null;
  };
  assignee?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug?: string | null;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  author?: (number | null) | Author;
  category?: (number | null) | Category;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  tagRelations?: (number | Tag)[] | null;
  contentType: 'news' | 'analysis' | 'guide' | 'tool' | 'comparison';
  publicReviewer?: (number | null) | Author;
  businessImpact?: string | null;
  readingTime?: number | null;
  reviewedAt?: string | null;
  aiDisclosure?: string | null;
  relatedServices?: (number | Service)[] | null;
  relatedArticles?: (number | Article)[] | null;
  publicCitations?:
    | {
        title: string;
        publisher: string;
        url: string;
        author?: string | null;
        publishedAt?: string | null;
        accessedAt: string;
        sourceType: string;
        isPrimary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  correctionHistory?:
    | {
        date: string;
        summary: string;
        responsible?: (number | null) | Author;
        id?: string | null;
      }[]
    | null;
  sources?: (number | Source)[] | null;
  dossier?: (number | null) | ResearchDossier;
  /**
   * Marca o artigo como destaque editorial (curadoria manual).
   */
  featured?: boolean | null;
  publishedAt?: string | null;
  workflowStatus: 'draft' | 'in_review' | 'approved' | 'published' | 'archived';
  seo?: {
    seoTitle?: string | null;
    seoDescription?: string | null;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  active?: boolean | null;
  indexable?: boolean | null;
  order?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  shortDescription: string;
  positioning?: string | null;
  targetAudience?: string | null;
  problems?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  deliverables?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  processSteps?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  capabilities?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  primaryCTAType?: ('diagnostic' | 'contact') | null;
  primaryCTALabel?: string | null;
  featured?: boolean | null;
  order?: number | null;
  active?: boolean | null;
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  clientDisplayName?: string | null;
  authorizationStatus: 'pending' | 'approved' | 'denied';
  challenge?: string | null;
  solution?: string | null;
  results?: string | null;
  metrics?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  period?: string | null;
  relatedServices?: (number | Service)[] | null;
  testimonial?: string | null;
  media?: (number | null) | Media;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
  };
  active?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  serviceInterest: string;
  operationalContext?: string | null;
  challenge: string;
  contactPreference: 'email' | 'phone' | 'whatsapp';
  source?: string | null;
  sourcePage?: string | null;
  sourceContent?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmTerm?: string | null;
  utmContent?: string | null;
  referrer?: string | null;
  consentVersion: string;
  consentTextHash: string;
  consentedAt: string;
  status?: ('new' | 'in_progress' | 'closed' | 'discarded') | null;
  idempotencyKey: string;
  retentionUntil: string;
  notificationStatus?: ('pending' | 'sent' | 'failed') | null;
  notificationAttempts?: number | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-outbox".
 */
export interface LeadOutbox {
  id: number;
  lead: number | Lead;
  type: 'commercial_notification';
  state?: ('pending' | 'sent' | 'failed') | null;
  attempts?: number | null;
  nextAttemptAt?: string | null;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'research-dossiers';
        value: number | ResearchDossier;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'lead-outbox';
        value: number | LeadOutbox;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  active?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  biography?: T;
  photo?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  title?: T;
  publisher?: T;
  url?: T;
  sourceType?: T;
  sourceLevel?: T;
  author?: T;
  publishedAt?: T;
  collectedAt?: T;
  editorialNotes?: T;
  reliability?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-dossiers_select".
 */
export interface ResearchDossiersSelect<T extends boolean = true> {
  topic?: T;
  summary?: T;
  keyFindings?:
    | T
    | {
        finding?: T;
        id?: T;
      };
  sources?: T;
  risksAndDivergences?: T;
  status?: T;
  provenance?:
    | T
    | {
        origin?: T;
        runId?: T;
        collectedAt?: T;
        notes?: T;
      };
  assignee?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  heroImage?: T;
  author?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  tagRelations?: T;
  contentType?: T;
  publicReviewer?: T;
  businessImpact?: T;
  readingTime?: T;
  reviewedAt?: T;
  aiDisclosure?: T;
  relatedServices?: T;
  relatedArticles?: T;
  publicCitations?:
    | T
    | {
        title?: T;
        publisher?: T;
        url?: T;
        author?: T;
        publishedAt?: T;
        accessedAt?: T;
        sourceType?: T;
        isPrimary?: T;
        id?: T;
      };
  correctionHistory?:
    | T
    | {
        date?: T;
        summary?: T;
        responsible?: T;
        id?: T;
      };
  sources?: T;
  dossier?: T;
  featured?: T;
  publishedAt?: T;
  workflowStatus?: T;
  seo?:
    | T
    | {
        seoTitle?: T;
        seoDescription?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  positioning?: T;
  targetAudience?: T;
  problems?:
    | T
    | {
        value?: T;
        id?: T;
      };
  deliverables?:
    | T
    | {
        value?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        value?: T;
        id?: T;
      };
  capabilities?:
    | T
    | {
        value?: T;
        id?: T;
      };
  primaryCTAType?: T;
  primaryCTALabel?: T;
  featured?: T;
  order?: T;
  active?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  clientDisplayName?: T;
  authorizationStatus?: T;
  challenge?: T;
  solution?: T;
  results?: T;
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  period?: T;
  relatedServices?: T;
  testimonial?: T;
  media?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  active?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  active?: T;
  indexable?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  serviceInterest?: T;
  operationalContext?: T;
  challenge?: T;
  contactPreference?: T;
  source?: T;
  sourcePage?: T;
  sourceContent?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmTerm?: T;
  utmContent?: T;
  referrer?: T;
  consentVersion?: T;
  consentTextHash?: T;
  consentedAt?: T;
  status?: T;
  idempotencyKey?: T;
  retentionUntil?: T;
  notificationStatus?: T;
  notificationAttempts?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-outbox_select".
 */
export interface LeadOutboxSelect<T extends boolean = true> {
  lead?: T;
  type?: T;
  state?: T;
  attempts?: T;
  nextAttemptAt?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}